version: "3"
services:
  mockit-routes:
    image: "mockit-routes"
    build: "mockit-routes"
    ports:
      - 3000:3000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-routes/configuration/routes.json
  mockit-server:
    image: "mockit-server"
    build: "server"
    ports:
      - 4000:4000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-server/configuration/routes.json
  mockit-client:
    image: "mockit-client"
    build: "client"
    ports:
      - 5000:3000
    environment:
      - REACT_APP_MOCKIT_SERVER_URL=http://10.115.1.130:3000
      - REACT_APP_MOCKIT_API_URL=http://10.115.1.130:4000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-client/src/config/routes.json
